SELECT * FROM chinook.Invoice;
SELECT COUNT(*) FROM CUSTOMER;
SELECT count(*) FROM GENRE;
SELECT * FROM PLAYLIST;
SELECT * FROM PLAYLISTTRACK;
SELECT * FROM Employee;
SELECT * FROM CHINOOK.TRACK;
SELECT distinct(i.Quantity) FROM chinook.invoiceline i;

#2
SELECT BILLINGCOUNTRY,
  	COUNT(INVOICEID)
FROM CHINOOK.INVOICE
GROUP BY 1 ORDER BY 2 DESC LIMIT 1;
#El país que tiene más facturas es USA con 91

#3
SELECT BILLINGCITY,
	COUNT(INVOICEID)
FROM CHINOOK.INVOICE
GROUP BY 1  
ORDER BY 2 DESC;
#La ciudad con más facturas es Paris con 14

#4
SELECT C.FIRSTNAME, C.LASTNAME, SUM(I.TOTAL) FROM CHINOOK.CUSTOMER C, CHINOOK.INVOICE I 
WHERE I.CUSTOMERID = C.CUSTOMERID 
GROUP BY C.CUSTOMERID
ORDER BY 3 DESC LIMIT 1;

#5
SELECT C.EMAIL, C.FIRSTNAME, C.LASTNAME, G.NAME
FROM CHINOOK.CUSTOMER C,
	CHINOOK.INVOICE I,
    CHINOOK.INVOICELINE IL,
    CHINOOK.TRACK T,
    CHINOOK.GENRE G
WHERE C.CUSTOMERID=I.CUSTOMERID
AND I.INVOICEID = IL.INVOICEID
AND IL.TRACKID = T.TRACKID
AND T.GENREID = G.GENREID
AND G.GENREID=1
GROUP BY C.CUSTOMERID
ORDER BY 2, 3
;

/*
SELECT COUNT(*) AS Total_Registros
FROM (
    SELECT c.customerId
    FROM CUSTOMER C
    JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
    JOIN INVOICELINE IL ON I.INVOICEID = IL.INVOICEID
    JOIN TRACK T ON IL.TRACKID = T.TRACKID
    JOIN GENRE G ON T.GENREID = G.GENREID
    WHERE G.GENREID = 6
    GROUP BY C.CUSTOMERID
) AS Customer_Genre_1;
*/

#6
SELECT A.NAME, G.NAME 
FROM CHINOOK.ARTIST A, CHINOOK.ALBUM AL, CHINOOK.TRACK T, CHINOOK.GENRE G 
WHERE A.ARTISTID = AL.ARTISTID
AND AL.ALBUMID = T.ALBUMID
AND T.GENREID = G.GENREID
AND G.GENREID = 1
GROUP BY A.NAME;

/*
SELECT COUNT(*) AS TOTAL_REGISTROS
FROM (
SELECT A.NAME 
FROM ARTIST A, ALBUM AL, TRACK T, GENRE G 
WHERE A.ARTISTID = AL.ARTISTID
AND AL.ALBUMID = T.ALBUMID
AND T.GENREID = G.GENREID
AND G.GENREID = 1
GROUP BY A.NAME
) AS ARTISTAS_ROCK
*/

#7
SELECT A.NAME,
SUM(I.UNITPRICE * I.QUANTITY) AS Total
FROM CHINOOK.ARTIST A, CHINOOK.ALBUM AL, CHINOOK.TRACK T, CHINOOK.INVOICELINE I
WHERE A.ARTISTID = AL.ARTISTID
AND AL.ALBUMID = T.ALBUMID
AND T.TRACKID = I.TRACKID
GROUP BY A.NAME
ORDER BY 2 DESC;

#8
SELECT I.BILLINGCOUNTRY,
SUM(IL.UNITPRICE * IL.QUANTITY) AS TOTAL
FROM CHINOOK.INVOICE I, CHINOOK.INVOICELINE IL
WHERE I.INVOICEID = IL.INVOICEID
AND I.BILLINGCOUNTRY = 'USA'
GROUP BY I.BILLINGCOUNTRY
ORDER BY 2 DESC;

#9
SELECT C.FIRSTNAME, C.LASTNAME, G.NAME, SUM(IL.UNITPRICE * IL.QUANTITY) AS TOTAL
FROM CHINOOK.CUSTOMER C, CHINOOK.INVOICE I, CHINOOK.INVOICELINE IL, CHINOOK.TRACK T, CHINOOK.GENRE G
WHERE C.CUSTOMERID = I.CUSTOMERID
AND I.INVOICEID = IL.INVOICEID
AND IL.TRACKID = T.TRACKID
AND T.GENREID = G.GENREID
GROUP BY 3
ORDER BY 4 DESC;

#10
SELECT COUNT(*), COUNTRY 
FROM CHINOOK.CUSTOMER
GROUP BY COUNTRY;

#SELECT * FROM CHINOOK.CUSTOMER WHERE COUNTRY = 'Canada'

#11
SELECT COUNT(*), G.NAME
FROM CHINOOK.TRACK T, CHINOOK.GENRE G
WHERE T.GENREID = G.GENREID
GROUP BY G.NAME
ORDER BY 1 DESC;



